# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 16:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=200, unique=True)),
                ('pc_lifecycle', models.BooleanField(verbose_name='Listed in PC Lifecycle Inventory')),
                ('property_control', models.BooleanField(verbose_name='Listed in Property Control Inventory')),
                ('owner', models.CharField(max_length=200, verbose_name='Primary User')),
                ('curator', models.CharField(max_length=200, verbose_name='Who is responsible for the hardware')),
                ('department', models.CharField(max_length=200, verbose_name='Department who owns the hardware')),
                ('org_code', models.CharField(max_length=200, verbose_name='Orginational Code')),
                ('location', models.CharField(max_length=200, verbose_name='Location of the hardware')),
                ('vendor', models.CharField(max_length=200, verbose_name='Vender the hardware was purchesed through')),
                ('vendor_serial_number', models.CharField(max_length=200, unique=True, verbose_name="Vender's serial number")),
                ('purchase_order', models.CharField(max_length=200, verbose_name='PO')),
                ('purchase_date', models.DateTimeField(verbose_name='Date of purchase')),
                ('purchase_cost', models.CharField(max_length=200, verbose_name='Cost of hardware')),
                ('funded_by', models.CharField(max_length=200, verbose_name='Source of funds used to purchase the hardware')),
                ('hardware_type', models.CharField(max_length=200)),
                ('hardware_make', models.CharField(max_length=200)),
                ('hardware_model', models.CharField(max_length=200)),
                ('hardware_serial_number', models.CharField(max_length=200, unique=True)),
                ('mac_wired', models.CharField(max_length=200, unique=True)),
                ('mac_wireless', models.CharField(max_length=200, unique=True)),
                ('processor', models.CharField(max_length=200)),
                ('harddrive', models.CharField(max_length=200)),
                ('ram', models.CharField(max_length=200)),
                ('graphics', models.CharField(max_length=200)),
                ('notes', models.TextField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField()),
                ('deleted_date', models.DateTimeField()),
                ('audited_date', models.DateTimeField()),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_user', to=settings.AUTH_USER_MODEL)),
                ('audited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audited_user', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_user', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modified_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComputerObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_name', models.CharField(max_length=200, unique=True)),
                ('os', models.CharField(max_length=200)),
                ('network_connection', models.CharField(choices=[('WD', 'Wired'), ('WL', 'Wireless'), ('None', 'No Network Connection')], max_length=30, verbose_name='Primary connection used by computer')),
                ('active_directory', models.BooleanField(verbose_name='Computer on the Domain and listed in Active Directory')),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4')),
                ('organizational_unit', models.CharField(max_length=200, verbose_name='OU location of the computer')),
                ('sccm', models.BooleanField(verbose_name='Computer is listed in SCCM')),
                ('jamf', models.BooleanField(verbose_name='Computer is listed in JAMF')),
                ('scep', models.BooleanField(verbose_name='Computer has SCEP installed and up-to-date')),
                ('identity_finder', models.BooleanField(verbose_name='Identity Finder installed')),
                ('notes', models.TextField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cos.Asset', verbose_name='Asset Tag')),
            ],
        ),
    ]
