# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 17:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='owner',
        ),
        migrations.AddField(
            model_name='asset',
            name='user',
            field=models.CharField(blank=True, max_length=200, verbose_name='Primary User'),
        ),
        migrations.AddField(
            model_name='computerobject',
            name='os_arch',
            field=models.CharField(blank=True, choices=[('x86', '32-Bit'), ('x64', '64-Bit'), ('none', 'No OS installed')], max_length=30, verbose_name='OS architecture'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='audited_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='audited_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asset',
            name='audited_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='curator',
            field=models.CharField(blank=True, max_length=200, verbose_name='Who is responsible for the hardware'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='deleted_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asset',
            name='deleted_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='department',
            field=models.CharField(blank=True, choices=[('dean', "Dean's office"), ('bot', 'Botany'), ('chem', 'Chemistry'), ('geo', 'Geosciences'), ('math', 'Mathematics'), ('dev_math', 'Developmental Math'), ('micro', 'Microbiology'), ('phys', 'Physics'), ('planet_phys', 'Planetarium'), ('zoo', 'Zoology'), ('csme', 'Center of Science and Math Education'), ('other', 'Other or Unknown Department'), ('None', 'No department')], max_length=200, verbose_name='Department who owns the hardware'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='funded_by',
            field=models.CharField(blank=True, max_length=200, verbose_name='Source of funds used to purchase the hardware'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='graphics',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='asset',
            name='harddrive',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='asset',
            name='hardware_make',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='asset',
            name='hardware_model',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='asset',
            name='hardware_serial_number',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='hardware_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Location of the hardware'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='mac_wired',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='mac_wireless',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='org_code',
            field=models.CharField(blank=True, choices=[('25000', "25000 - Dean's Office"), ('25100', '25100 - Botany'), ('25200', '25200 - Chemistry'), ('25300', '25300 - Geosciences'), ('25400', '25400 - Mathematics'), ('25403', '25403 - Developmental Math'), ('25500', '25500 - Microbiology'), ('25600', '25600 - Physics'), ('25601', '25601 - Planetarium'), ('25700', '25700 - Zoology'), ('25801', '25801 - CSME'), ('None', 'No organization code')], max_length=200, verbose_name='Orginational Code'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='processor',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_cost',
            field=models.CharField(blank=True, max_length=200, verbose_name='Cost of hardware'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_date',
            field=models.DateTimeField(blank=True, verbose_name='Date of purchase'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_order',
            field=models.CharField(blank=True, max_length=200, verbose_name='PO'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='ram',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='asset',
            name='vendor',
            field=models.CharField(blank=True, max_length=200, verbose_name='Vender the hardware was purchesed through'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='vendor_serial_number',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name="Vender's serial number"),
        ),
        migrations.AlterField(
            model_name='computerobject',
            name='computer_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='computerobject',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='computerobject',
            name='network_connection',
            field=models.CharField(blank=True, choices=[('WD', 'Wired'), ('WL', 'Wireless'), ('none', 'No Network Connection')], max_length=30, verbose_name='Primary connection used by computer'),
        ),
        migrations.AlterField(
            model_name='computerobject',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='computerobject',
            name='organizational_unit',
            field=models.CharField(blank=True, max_length=200, verbose_name='OU location of the computer'),
        ),
        migrations.AlterField(
            model_name='computerobject',
            name='os',
            field=models.CharField(blank=True, choices=[('osx_10.5', 'Mac OS X Leopard'), ('osx_10.6', 'Mac OS X Snow Leopard'), ('osx_10.7', 'Mac OS X Lion'), ('osx_10.8', 'Mac OS X Mountain Lion'), ('osx_10.9', 'Mac OS X Macericks'), ('osx_10.10', 'Mac OS X Yosemite'), ('osx_10.11', 'Mac OS X El Capitan'), ('osx_10.12', 'Mac OS X Sierra'), ('osx_10.13', 'Mac OS X High Sierra'), ('win_xp_home', 'Windows XP Home'), ('win_xp_pro', 'Windows XP Pro'), ('win_vista_home', 'Windows Vista Home'), ('win_vista_pro', 'Windows Vista Pro'), ('win_vista_ent', 'Windows Vista Enterprise'), ('win_7_home', 'Windows 7 Home'), ('win_7_pro', 'Windows 7 Pro'), ('win_7_ent', 'Windows 7 Enterprise'), ('win_8', 'Windows 8'), ('win_8_pro', 'Windows 8 Pro'), ('win_8_ent', 'Windows 8 Enterprise'), ('win_8_1', 'Windows 8.1'), ('win_8_1_pro', 'Windows 8.1 Pro'), ('win_8_1_ent', 'Windows 8.1 Enterprise'), ('win_10_home', 'Windows 10 Home'), ('win_10_pro', 'Windows 10 Pro'), ('win_10_ent', 'Windows 10 Enterprise'), ('win_10_ent_ltsb', 'Windows 10 Enterprise LTSB'), ('linux', 'Linux Distro'), ('other', 'Other OS'), ('none', 'No OS installed')], max_length=200, verbose_name='Installed OS'),
        ),
    ]
