# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 23:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='asset_status',
        ),
        migrations.RemoveField(
            model_name='historicalasset',
            name='asset_status',
        ),
    ]
