# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cos', '0002_auto_20170815_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='inventory_system_current',
        ),
        migrations.RemoveField(
            model_name='historicalasset',
            name='inventory_system_current',
        ),
    ]
