# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cos', '0003_auto_20170714_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='purchase_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of purchase'),
        ),
    ]
