# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cos', '0003_auto_20170816_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='eligible_upgrade',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Upgrade eligibility'),
        ),
        migrations.AddField(
            model_name='asset',
            name='eligible_upgrade_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Upgrade eligibility date'),
        ),
        migrations.AddField(
            model_name='asset',
            name='requisition_number',
            field=models.CharField(blank=True, max_length=200, verbose_name='Requisition number'),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='eligible_upgrade',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Upgrade eligibility'),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='eligible_upgrade_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Upgrade eligibility date'),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='requisition_number',
            field=models.CharField(blank=True, max_length=200, verbose_name='Requisition number'),
        ),
    ]
