# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cos', '0004_auto_20170816_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='eligible_upgrade',
            field=models.IntegerField(blank=True, choices=[(0, '5 years'), (1, '4 years')], default=0, null=True, verbose_name='Upgrade eligibility'),
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='eligible_upgrade',
            field=models.IntegerField(blank=True, choices=[(0, '5 years'), (1, '4 years')], default=0, null=True, verbose_name='Upgrade eligibility'),
        ),
    ]
