# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cos', '0004_auto_20170714_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='audited_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
