# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cos', '0006_auto_20170714_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='hardware_serial_number',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='mac_wired',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='mac_wireless',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
