# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cos', '0008_auto_20170714_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computerobject',
            name='asset',
        ),
        migrations.AddField(
            model_name='asset',
            name='active_directory',
            field=models.BooleanField(default=False, verbose_name='Computer on the Domain and listed in Active Directory'),
        ),
        migrations.AddField(
            model_name='asset',
            name='computer_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='asset',
            name='identity_finder',
            field=models.BooleanField(default=False, verbose_name='Identity Finder installed'),
        ),
        migrations.AddField(
            model_name='asset',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
        migrations.AddField(
            model_name='asset',
            name='jamf',
            field=models.BooleanField(default=False, verbose_name='Computer is listed in JAMF'),
        ),
        migrations.AddField(
            model_name='asset',
            name='network_connection',
            field=models.CharField(blank=True, choices=[('WD', 'Wired'), ('WL', 'Wireless'), ('none', 'No Network Connection')], max_length=30, verbose_name='Primary connection used by computer'),
        ),
        migrations.AddField(
            model_name='asset',
            name='organizational_unit',
            field=models.CharField(blank=True, max_length=200, verbose_name='OU location of the computer'),
        ),
        migrations.AddField(
            model_name='asset',
            name='os',
            field=models.CharField(blank=True, choices=[('osx_10.5', 'Mac OS X Leopard'), ('osx_10.6', 'Mac OS X Snow Leopard'), ('osx_10.7', 'Mac OS X Lion'), ('osx_10.8', 'Mac OS X Mountain Lion'), ('osx_10.9', 'Mac OS X Macericks'), ('osx_10.10', 'Mac OS X Yosemite'), ('osx_10.11', 'Mac OS X El Capitan'), ('osx_10.12', 'Mac OS X Sierra'), ('osx_10.13', 'Mac OS X High Sierra'), ('win_xp_home', 'Windows XP Home'), ('win_xp_pro', 'Windows XP Pro'), ('win_vista_home', 'Windows Vista Home'), ('win_vista_pro', 'Windows Vista Pro'), ('win_vista_ent', 'Windows Vista Enterprise'), ('win_7_home', 'Windows 7 Home'), ('win_7_pro', 'Windows 7 Pro'), ('win_7_ent', 'Windows 7 Enterprise'), ('win_8', 'Windows 8'), ('win_8_pro', 'Windows 8 Pro'), ('win_8_ent', 'Windows 8 Enterprise'), ('win_8_1', 'Windows 8.1'), ('win_8_1_pro', 'Windows 8.1 Pro'), ('win_8_1_ent', 'Windows 8.1 Enterprise'), ('win_10_home', 'Windows 10 Home'), ('win_10_pro', 'Windows 10 Pro'), ('win_10_ent', 'Windows 10 Enterprise'), ('win_10_ent_ltsb', 'Windows 10 Enterprise LTSB'), ('linux', 'Linux Distro'), ('other', 'Other OS'), ('none', 'No OS installed')], max_length=200, verbose_name='Installed OS'),
        ),
        migrations.AddField(
            model_name='asset',
            name='os_arch',
            field=models.CharField(blank=True, choices=[('x86', '32-Bit'), ('x64', '64-Bit'), ('none', 'No OS installed')], max_length=30, verbose_name='OS architecture'),
        ),
        migrations.AddField(
            model_name='asset',
            name='sccm',
            field=models.BooleanField(default=False, verbose_name='Computer is listed in SCCM'),
        ),
        migrations.AddField(
            model_name='asset',
            name='scep',
            field=models.BooleanField(default=False, verbose_name='Computer has SCEP installed and up-to-date'),
        ),
        migrations.DeleteModel(
            name='ComputerObject',
        ),
    ]
