# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cos', '0009_auto_20170731_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='pc_lifecycle',
            field=models.BooleanField(default=False, verbose_name='Listed in PC Lifecycle Inventory'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='property_control',
            field=models.BooleanField(default=False, verbose_name='Listed in Property Control Inventory'),
        ),
    ]
