# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cos', '0013_auto_20170731_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='computer_role',
            new_name='asset_role',
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('good', 'Good'), ('worn', 'Worn out'), ('broken', 'Broken')], max_length=200, verbose_name='Hardware condition'),
        ),
    ]
