# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cos', '0014_auto_20170731_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='asset_condition',
            new_name='equipment_condition',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='asset_role',
            new_name='equipment_role',
        ),
    ]
