# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cos', '0015_auto_20170731_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='pc_lifecycle',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='property_control',
        ),
        migrations.AddField(
            model_name='asset',
            name='inventory_system',
            field=models.CharField(blank=True, choices=[('pc_lifecycle', 'PC Lifecycle'), ('property_control', 'Property Control'), ('old', 'Old Inventory Tag')], max_length=200, verbose_name='Inventory System'),
        ),
    ]
