# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cos', '0016_auto_20170731_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='inventory_system_current',
            field=models.BooleanField(default=False, verbose_name='Inventory System Up-To-Date'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='equipment_role',
            field=models.CharField(blank=True, choices=[('faculty_main', 'Faculty Main Computer'), ('faculty_secondary', 'Faculty Secondary Computer'), ('classroom_computer', 'Classroom Computer'), ('instrument_computer', 'Instrument Computer'), ('lab_research', 'Research Lab Computer'), ('lab_open', 'Open Lab Computer'), ('lab_closed', 'Closed Lab Computer'), ('department_travel', 'Department Travel Computer'), ('staff_main', 'Staff Main Computer'), ('staff_secondary', 'Staff Secondary Computer'), ('stock', 'In Stock Computer'), ('surplus', 'Surplused Computer'), ('other', 'Other Computer')], max_length=200, verbose_name='What is the primary role of the computer'),
        ),
    ]
