# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cos', '0017_auto_20170731_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
