# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cos', '0018_auto_20170801_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='hardware_type',
            field=models.CharField(blank=True, max_length=200, verbose_name='Mac or PC'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='vendor_serial_number',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name="Vender's serial number"),
        ),
    ]
