# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cos', '0020_auto_20170807_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='hardware_condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('good', 'Good'), ('used', 'Used'), ('worn', 'Worn out'), ('broken', 'Broken')], max_length=200, verbose_name='Hardware condition'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='hardware_role',
            field=models.CharField(blank=True, choices=[('faculty_main', 'Faculty Main'), ('faculty_secondary', 'Faculty Secondary'), ('classroom_hardware', 'Classroom'), ('instrument_hardware', 'Instrument'), ('lab_research', 'Research Lab'), ('lab_open', 'Open Lab'), ('lab_closed', 'Closed Lab'), ('department_travel', 'Department Travel'), ('staff_main', 'Staff Main'), ('staff_secondary', 'Staff Secondary'), ('stock', 'In Stock'), ('surplus', 'Surplused'), ('other', 'Other')], max_length=200, verbose_name='Hardware primary role'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='inventory_system',
            field=models.CharField(blank=True, choices=[('pc_lifecycle', 'PC Lifecycle'), ('property_control', 'Property Control'), ('old', 'Old Inventory Tag'), ('None', 'No Tag')], max_length=200, verbose_name='Inventory System'),
        ),
    ]
