# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cos', '0021_auto_20170807_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='active_directory',
            field=models.BooleanField(default=False, verbose_name='Managed on the Domain'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='curator',
            field=models.CharField(blank=True, max_length=200, verbose_name='Curator'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='department',
            field=models.CharField(blank=True, choices=[('dean', "Dean's office"), ('bot', 'Botany'), ('chem', 'Chemistry'), ('geo', 'Geosciences'), ('math', 'Mathematics'), ('dev_math', 'Developmental Math'), ('micro', 'Microbiology'), ('phys', 'Physics'), ('planet_phys', 'Planetarium'), ('zoo', 'Zoology'), ('csme', 'Center of Science and Math Education'), ('other', 'Other or Unknown Department'), ('None', 'No department')], max_length=200, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='hardware_condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('good', 'Good'), ('used', 'Used'), ('worn', 'Worn out'), ('broken', 'Broken')], max_length=200, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='network_connection',
            field=models.CharField(blank=True, choices=[('WD', 'Wired'), ('WL', 'Wireless'), ('none', 'No Network Connection')], max_length=30, verbose_name='Network connection'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='organizational_unit',
            field=models.CharField(blank=True, max_length=200, verbose_name='OU location'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_cost',
            field=models.CharField(blank=True, max_length=200, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='vendor',
            field=models.CharField(blank=True, max_length=200, verbose_name='Vendor'),
        ),
    ]
