# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cos', '0022_auto_20170807_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='hardware_type',
            field=models.CharField(choices=[('desktop', 'Desktop'), ('laptop', 'Laptop'), ('tablet', 'Tablet'), ('printer', 'Printer'), ('projector', 'Projector'), ('tv', 'TV or Monitor'), ('extron', 'Extron'), ('doc_cam', 'Document Camera'), ('camera', 'Camera'), ('other', 'Other')], max_length=200),
        ),
    ]
