# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cos', '0024_auto_20170808_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='hardware_condition',
            field=models.CharField(blank=True, choices=[('good', 'Good'), ('old', 'Old'), ('broken', 'Broken')], max_length=200, verbose_name='Condition'),
        ),
    ]
