# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='status',
            field=models.CharField(choices=[('current', 'Current'), ('not_current', 'Not Employed'), ('moved', 'Moved Departments'), ('retired', 'Retired'), ('sabbatical', 'Sabbatical'), ('temporary', 'Temporary')], max_length=200),
        ),
        migrations.AlterField(
            model_name='historicaldirectory',
            name='status',
            field=models.CharField(choices=[('current', 'Current'), ('not_current', 'Not Employed'), ('moved', 'Moved Departments'), ('retired', 'Retired'), ('sabbatical', 'Sabbatical'), ('temporary', 'Temporary')], max_length=200),
        ),
    ]
