# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldirectory',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
