# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory_app', '0002_auto_20170830_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directory',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicaldirectory',
            name='status',
        ),
        migrations.AddField(
            model_name='directory',
            name='current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicaldirectory',
            name='current',
            field=models.BooleanField(default=True),
        ),
    ]
