# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0002_auto_20170829_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='eligible_upgrade_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Upgrade eligibility date'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of purchase'),
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='eligible_upgrade_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Upgrade eligibility date'),
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='purchase_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of purchase'),
        ),
    ]
