# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0003_auto_20170829_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='os',
            field=models.CharField(blank=True, choices=[('osx_10.5', 'Mac OS X Leopard (10.5)'), ('osx_10.6', 'Mac OS X Snow Leopard (10.6)'), ('osx_10.7', 'Mac OS X Lion (10.7)'), ('osx_10.8', 'Mac OS X Mountain Lion (10.8)'), ('osx_10.9', 'Mac OS X Macericks (10.9)'), ('osx_10.10', 'Mac OS X Yosemite (10.10)'), ('osx_10.11', 'Mac OS X El Capitan (10.11)'), ('osx_10.12', 'Mac OS X Sierra (10.12)'), ('osx_10.13', 'Mac OS X High Sierra (10.13)'), ('win_xp_home', 'Windows XP Home'), ('win_xp_pro', 'Windows XP Pro'), ('win_vista_home', 'Windows Vista Home'), ('win_vista_pro', 'Windows Vista Pro'), ('win_vista_ent', 'Windows Vista Enterprise'), ('win_7_home', 'Windows 7 Home'), ('win_7_pro', 'Windows 7 Pro'), ('win_7_ent', 'Windows 7 Enterprise'), ('win_8', 'Windows 8'), ('win_8_pro', 'Windows 8 Pro'), ('win_8_ent', 'Windows 8 Enterprise'), ('win_8_1', 'Windows 8.1'), ('win_8_1_pro', 'Windows 8.1 Pro'), ('win_8_1_ent', 'Windows 8.1 Enterprise'), ('win_10_home', 'Windows 10 Home'), ('win_10_pro', 'Windows 10 Pro'), ('win_10_ent', 'Windows 10 Enterprise'), ('win_10_ent_ltsb', 'Windows 10 Enterprise LTSB'), ('linux', 'Linux Distro'), ('other', 'Other OS'), ('none', 'No OS installed')], max_length=200, verbose_name='Installed OS'),
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='os',
            field=models.CharField(blank=True, choices=[('osx_10.5', 'Mac OS X Leopard (10.5)'), ('osx_10.6', 'Mac OS X Snow Leopard (10.6)'), ('osx_10.7', 'Mac OS X Lion (10.7)'), ('osx_10.8', 'Mac OS X Mountain Lion (10.8)'), ('osx_10.9', 'Mac OS X Macericks (10.9)'), ('osx_10.10', 'Mac OS X Yosemite (10.10)'), ('osx_10.11', 'Mac OS X El Capitan (10.11)'), ('osx_10.12', 'Mac OS X Sierra (10.12)'), ('osx_10.13', 'Mac OS X High Sierra (10.13)'), ('win_xp_home', 'Windows XP Home'), ('win_xp_pro', 'Windows XP Pro'), ('win_vista_home', 'Windows Vista Home'), ('win_vista_pro', 'Windows Vista Pro'), ('win_vista_ent', 'Windows Vista Enterprise'), ('win_7_home', 'Windows 7 Home'), ('win_7_pro', 'Windows 7 Pro'), ('win_7_ent', 'Windows 7 Enterprise'), ('win_8', 'Windows 8'), ('win_8_pro', 'Windows 8 Pro'), ('win_8_ent', 'Windows 8 Enterprise'), ('win_8_1', 'Windows 8.1'), ('win_8_1_pro', 'Windows 8.1 Pro'), ('win_8_1_ent', 'Windows 8.1 Enterprise'), ('win_10_home', 'Windows 10 Home'), ('win_10_pro', 'Windows 10 Pro'), ('win_10_ent', 'Windows 10 Enterprise'), ('win_10_ent_ltsb', 'Windows 10 Enterprise LTSB'), ('linux', 'Linux Distro'), ('other', 'Other OS'), ('none', 'No OS installed')], max_length=200, verbose_name='Installed OS'),
        ),
    ]
